import type { Metadata } from "next";
import Link from "next/link";
import { PageHero } from "@/components/page-hero";
import { SectionHeading } from "@/components/section-heading";
import { portfolioItems } from "@/lib/site-data";
import { applications } from "@/lib/ax-data";
export const metadata: Metadata = { title: "제조 AX 적용 분야", description: "생산 보고서와 품질문서 검색부터 납기·불량·재고·설비 분석까지 10가지 제조 AX 적용 분야" };
export default function PortfolioPage() {
  return <main id="main-content"><PageHero eyebrow="Manufacturing applications" title="현장 업무에 맞는 AX 적용 분야" description="보고서와 문서 검색을 우선 검토합니다. 예측·영상·센서 분석은 데이터와 현장 조건을 확인한 뒤 확장합니다." /><section className="section"><div className="container"><SectionHeading eyebrow="Where to begin" title="우선 적용과 확장 방향" description="아래 내용은 적용 제안이며 고객 구축 실적이나 성과를 뜻하지 않습니다." /><div className="content-grid">{portfolioItems.map((item) => <Link className="content-card" href={`/portfolio/${item.slug}`} key={item.slug}><div className={`visual visual--${item.tone}`}><span>{item.label}</span></div><div><h2>{item.title}</h2><p>{item.summary}</p><strong>적용 흐름 →</strong></div></Link>)}</div></div></section><section className="section section--soft"><div className="container"><SectionHeading eyebrow="10 opportunities" title="데이터와 검증 기준으로 선택합니다" description="필요 자료를 갖추고 작은 범위에서 평가합니다. 대상 업무·품목·공장·연동·사용자 수는 착수 전에 협의합니다." /><div className="application-grid">{applications.map((item, index) => <article className="application-card" key={item.title}><div className="application-meta"><span>{String(index + 1).padStart(2, "0")} / {item.domain}</span><b>{item.stage}</b></div><h3>{item.title}</h3><p>{item.summary}</p><dl><dt>필요 데이터</dt><dd>{item.data}</dd><dt>검증 지표</dt><dd>{item.metric}</dd></dl><p className="application-condition">{item.condition}</p></article>)}</div></div></section><section className="sub-cta"><div className="container"><h2>보유한 자료에서 적용할 일을 찾습니다.</h2><p>현재 사용하는 시스템과 반복되는 문제를 알려주세요.</p><Link className="button button--gold" href="/diagnosis">AX 사전진단 신청</Link></div></section></main>;
}
