import Link from "next/link";
import { SectionHeading } from "@/components/section-heading";
import { services, blogPosts } from "@/lib/site-data";
import { implementationSteps } from "@/lib/ax-data";

export default function HomePage() {
  return (
    <main id="main-content">
      <section className="hero hero--home"><div className="container hero__grid">
        <div><p className="eyebrow">Manufacturing AX / INGIN I&amp;S</p><h1>현장의 기록을<br /><span>일하는 AI로.</span></h1><p className="lead">중소 제조기업의 생산·품질·공급망 데이터를 연결합니다. 매일 쓰는 생산 보고서와 품질문서 검색부터, 현장에서 확인할 수 있는 변화로 시작합니다.</p><div className="button-row"><Link className="button button--gold" href="/diagnosis">우리 공장 AX 진단</Link><Link className="button button--ghost" href="/services">서비스 살펴보기 ↗</Link></div><p className="hero-note">엑셀·CSV부터 기존 ERP·MES·QMS까지, 현재 자료에서 시작합니다.</p></div>
        <div className="ax-console" aria-label="제조 업무 AI 도우미의 업무 흐름 예시"><div className="console-top"><span className="status-dot" /> MANUFACTURING WORKSPACE <small>업무 흐름 예시</small></div><div className="console-heading"><span>생산 · 품질 · 공급망</span><h2>데이터가 판단으로<br />이어지는 흐름</h2></div><div className="console-sources"><span>Excel / CSV</span><span>ERP / MES</span><span>승인 품질문서</span></div><div className="console-line" aria-hidden="true">↓</div><div className="console-task"><span>01 / PMS</span><h3>일일 생산 보고서</h3><p>실적 집계 <b>→</b> 설명 초안 <b>→</b> 담당자 확인</p><small>숫자는 계산으로 · 설명은 AI로</small></div><div className="console-task"><span>02 / QMS</span><h3>품질문서 검색</h3><p>승인 문서 <b>→</b> 근거·버전 <b>→</b> 검토</p><small>권한에 맞는 자료와 근거 확인</small></div><div className="console-footer"><span>HUMAN IN THE LOOP</span><b>최종 판단은 현장 담당자가</b></div></div>
      </div></section>
      <div className="domain-strip"><div className="container"><p>제조 업무를 연결하는 세 가지 축</p><span><b>PMS</b> 생산관리</span><span><b>QMS</b> 품질관리</span><span><b>SCM</b> 공급망관리</span></div></div>
      <section className="section section--soft"><div className="container"><SectionHeading eyebrow="Start with your daily work" title="매일 반복되는 이 업무부터 바꿉니다" description="생산관리자·품질관리자·구매담당자가 이미 기록하고 있는 자료에서 적용할 일을 찾습니다." /><div className="problem-grid"><article><b>01 / 생산</b><h3>보고서에 쓰는 시간</h3><p>여러 엑셀과 시스템에서 실적을 모으고 숫자를 맞추고 보고 문장을 작성하는 반복 업무.</p></article><article><b>02 / 품질</b><h3>찾기 어려운 검사기준</h3><p>어느 문서가 최신인지, 과거에는 어떻게 대응했는지 확인하는 데 걸리는 시간.</p></article><article><b>03 / 공급망</b><h3>늦게 보이는 납기 위험</h3><p>생산 지연과 자재 도착 정보가 나뉘어 긴급 대응이 반복되는 현장.</p></article></div></div></section>
      <section className="section"><div className="container"><SectionHeading eyebrow="First offering" title="제조 업무 AI 도우미" description="첫 적용은 보고서 자동 작성과 품질문서 검색입니다. 한 공장, 한 업무부터 효과를 확인합니다." /><div className="offering-grid"><article className="offering-card"><span className="badge">01 / PMS · AX</span><h3>일일 생산 보고서<br />자동 작성</h3><p>작업지시와 실적을 연결해 계획 대비 결과를 집계합니다. AI가 설명 초안을 만들고 담당자가 확인합니다.</p><ul><li>계획·실적·불량·중단 사유 집계</li><li>DB 조회와 계산으로 수치 확정</li><li>집계부터 수정까지 작성시간 비교</li></ul><Link className="text-link" href="/portfolio/production-report">적용 흐름 보기 →</Link></article><article className="offering-card offering-card--green"><span className="badge">02 / QMS · AX</span><h3>품질문서 검색과<br />고객 대응서 초안</h3><p>승인된 작업표준과 검사기준을 근거·버전과 함께 찾습니다. 과거 대응 자료로 초안 작성을 지원합니다.</p><ul><li>권한에 맞는 승인 문서 검색</li><li>문서 근거와 버전 표시</li><li>담당자 검토 후 대응서 활용</li></ul><Link className="text-link" href="/portfolio/quality-document-search">적용 흐름 보기 →</Link></article></div></div></section>
      <section className="section section--navy"><div className="container"><SectionHeading eyebrow="A practical path" title="진단하고, 작게 검증하고, 확장합니다" description="현재 업무와 자료를 확인해 도입 범위를 정합니다." /><div className="journey-grid">{implementationSteps.map((step, index) => <article key={step.title}><span>0{index + 1}</span><small>{step.period}</small><h3>{step.title}</h3><p>{step.description}</p></article>)}</div><p className="section-note">기간은 계획 기준이며 데이터 상태와 연동 범위에 따라 협의합니다. 진단·시범 검증·본 구축은 각각 범위와 비용을 정합니다.</p><Link className="button button--ghost" href="/diagnosis">AX 진단과 도입 절차 →</Link></div></section>
      <section className="section"><div className="container"><SectionHeading eyebrow="Connected services" title="기존 데이터에서 분석까지" description="시스템이 있으면 연동하고, 없으면 필요한 최소 기능부터 설계합니다." /><div className="card-grid">{services.map((service, index) => <Link className="service-card" href={`/services/${service.slug}`} key={service.slug}><span>0{index + 1}</span><h3>{service.title}</h3><p>{service.summary}</p><strong>서비스 상세 →</strong></Link>)}</div></div></section>
      <section className="section section--soft"><div className="container split-feature"><div><p className="eyebrow">Designed for the shop floor</p><h2>근거를 보여주고,<br />사람이 결정합니다.</h2><p>생산 수량·원가·재고는 계산으로 처리하고 AI는 설명·검색·초안을 지원합니다. 예측은 실제 이력으로 평가하며 현장 담당자가 최종 판단합니다.</p><Link className="text-link" href="/portfolio">10가지 제조 AX 적용 분야 →</Link></div><div className="trust-list"><article><span>01</span><div><h3>수치와 문서 근거</h3><p>확정 집계와 승인 문서·버전을 확인합니다.</p></div></article><article><span>02</span><div><h3>데이터와 권한</h3><p>기업별 분리와 역할별 접근권한을 설계합니다.</p></div></article><article><span>03</span><div><h3>측정과 현장 교육</h3><p>시간·오류·수정 기록을 비교하고 사용을 지원합니다.</p></div></article></div></div></section>
      <section className="section"><div className="container"><SectionHeading eyebrow="Field notes" title="제조 AX를 준비하는 방법" /><div className="blog-grid">{blogPosts.slice(0, 3).map((post) => <Link href={`/blog/${post.slug}`} key={post.slug}><span>{post.category}</span><h3>{post.title}</h3><p>{post.summary}</p><strong>글 읽기 →</strong></Link>)}</div></div></section>
      <section className="final-cta"><div className="container"><p className="eyebrow">Start with one task</p><h2>우리 공장의 반복 업무,<br />하나부터 함께 검토해요.</h2><p>현재 사용 중인 자료와 가장 시간이 많이 드는 업무를 알려주세요. 적용 가능성과 시범 검증 범위를 함께 확인합니다.</p><div className="button-row"><Link className="button button--gold" href="/contact">AX 도입 상담</Link><Link className="button button--ghost" href="/education">실무 교육·컨설팅</Link></div></div></section>
    </main>
  );
}
